name:                wai-project
version:             0.1.0.0
github:              "githubuser/wai-project"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wai-project#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- cookie
- scotty-cookie
- time
- time-lens
- mtl
- data-has
- string-random
- wai
- wai-extra
- warp
- scotty
- blaze-html
- blaze-builder
- blaze-markup
- digestive-functors-aeson
- aeson
- pcre-heavy
- lucid
- lucid-extras
- text
- jose-jwt
- cryptonite
- data-has
- aeson
- wai-cors
- digestive-functors
- digestive-functors-aeson
- digestive-functors-scotty
- Spock
- Spock-lucid
- uuid
- regex-compat
- http-types
- servant       
- servant-server

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - ExtendedDefaultRules

library:
  source-dirs: src

executables:
  wai-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-project

tests:
  wai-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai-project
